### ISSUE TITLE
menuconfig 74880 >>115200

### ISSUE THREAD

**Issue by exrector** [espressif/esp-homekit-sdk#70] opened 2021-09-28 16:30 UTC
There is a need to change the values manually in the file.

**Comment by shahpiyushv** [comment] 2021-09-28 16:43
@exrector , can you elaborate a bit more on what exactly the issue is?

**Comment by exrector** [comment] 2021-09-28 18:40
@shahpiyushv 
every time make menuconfig I set all the values to 115200
make flash-all OK
monitor-nothing is clear, garbage
I check sdkconfig and do autocorrect 74880 >> 115200
make flash-all OK
monitor-all OK

I can give you more details but tomorrow

**Comment by shahpiyushv** [comment] 2022-09-27 16:29
Closing this as no further information was received

**Closed by shahpiyushv** 2022-09-27 16:29 UTC
